language: node_js
node_js:
  - 10

if: tag IS present
deploy:
  provider: npm
  access: public
  email: mr.muzea@gmail.com
  api_key:
    secure: RDPhqjLmvoIHYRPYenMaZuvdd7gRpE3xsrA8rfCIYkRK0/BHtOK257lG3ej1xz10nkMk/6PXwv8/WRtNet2+/zAd2y0Ft/cwZD/TLzS3aC9an6XPgFYa8NlLl0fJzwEd2Ntk4rW4nKOYzJrWIOIpwjRiPC8+4VYuMOMmTFCNiMH5YLbdtyQ9sgu4m2Ghj04uQPXWt1Pg8aKpR2wb6GJnW/aEjgBoYmvDhD/oRgOQtzEcpQ1itA+ClGgsCxoUfTUXF2rFpG299TytC8OXpSVmnPHuMpC0jQ+TUGUhR2H+gXwjyjs/3kUAdYIfV1lOA1nLxwC06LtwSK8F1l5H0hoH3htYh0rNmD80CSZLZ9k1d6BXXfPwXsYP4ZM5XzsGgGwlDl45IOGX/4CoSMATHNvWlgOKjjtpVolO697QBVAajDCedgfwqPNn2lh8a/viW8L8V88QlKp5zp0zHct6CtKhcmqW8UqjLWM8125ln3A73mhzuxZrvRPMG9el+Q2erfRBZF3sA0U+dg6tBUR/Ys2A7W29AWbZr1FMNv9DS6Ecq/RXdSltLBXSkL2O2q3RryPLxBCJjHPXJrE5CpN2t4ymUtE1WRNFZeoqFyqWeDCl4/aFYCIT5jA6+VUY3M9rDlGGiRo6HxOWwj3Mu5aLsLsB9CxhcCMAY5tpbiB3RNi00mc=
