module.exports = [
  {
    "name": "Ecs",
    "version": "2014-05-26",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云服务器",
    "showNameEn": "Elastic Compute Service",
    "shortName": "ECS",
    "apiDocOverviewId": "25485",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": "DescribePrice,DescribeRenewalPrice",
    "endpoint": {
      "default": "https://ecs.aliyuncs.com",
      "cn-hangzhou": "https://ecs.aliyuncs.com",
      "cn-qingdao": "https://ecs.aliyuncs.com",
      "cn-beijing": "https://ecs.aliyuncs.com",
      "cn-zhangjiakou": "https://ecs.cn-zhangjiakou.aliyuncs.com",
      "cn-huhehaote": "https://ecs.cn-huhehaote.aliyuncs.com",
      "cn-shanghai": "https://ecs.aliyuncs.com",
      "cn-shenzhen": "https://ecs.aliyuncs.com",
      "cn-hongkong": "https://ecs.aliyuncs.com",
      "ap-southeast-1": "https://ecs.aliyuncs.com",
      "ap-southeast-2": "https://ecs.ap-southeast-2.aliyuncs.com",
      "ap-southeast-3": "https://ecs.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://ecs.ap-southeast-5.aliyuncs.com",
      "ap-northeast-1": "https://ecs.ap-northeast-1.aliyuncs.com",
      "eu-west-1": "https://ecs.eu-west-1.aliyuncs.com",
      "us-west-1": "https://ecs.aliyuncs.com",
      "us-east-1": "https://ecs.aliyuncs.com",
      "eu-central-1": "https://ecs.eu-central-1.aliyuncs.com",
      "me-east-1": "https://ecs.me-east-1.aliyuncs.com",
      "ap-south-1": "https://ecs.ap-south-1.aliyuncs.com",
      "cn-shanghai-finance-1": "https://ecs.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://ecs.aliyuncs.com"
    }
  },
  {
    "name": "Ess",
    "version": "2014-08-28",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "弹性伸缩",
    "showNameEn": "Auto Scaling",
    "shortName": "ESS",
    "apiDocOverviewId": "25925",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://ess.aliyuncs.com",
      "cn-zhangjiakou": "https://ess.cn-zhangjiakou.aliyuncs.com",
      "ap-northeast-1": "https://ess.ap-northeast-1.aliyuncs.com",
      "ap-southeast-2": "https://ess.ap-southeast-2.aliyuncs.com",
      "eu-central-1": "https://ess.eu-central-1.aliyuncs.com",
      "me-east-1": "https://ess.me-east-1.aliyuncs.com",
      "ap-southeast-3": "https://ess.ap-southeast-3.aliyuncs.com",
      "cn-huhehaote": "https://ess.cn-huhehaote.aliyuncs.com",
      "ap-south-1": "https://ess.ap-south-1.aliyuncs.com",
      "ap-southeast-5": "https://ess.ap-southeast-5.aliyuncs.com",
      "cn-hangzhou": "https://ess.aliyuncs.com",
      "cn-qingdao": "https://ess.aliyuncs.com",
      "cn-beijing": "https://ess.aliyuncs.com",
      "cn-shanghai": "https://ess.aliyuncs.com",
      "cn-shenzhen": "https://ess.aliyuncs.com",
      "cn-hongkong": "https://ess.aliyuncs.com",
      "cn-chengdu": "https://ess.cn-chengdu.aliyuncs.com",
      "ap-southeast-1": "https://ess.aliyuncs.com",
      "us-east-1": "https://ess.aliyuncs.com",
      "us-west-1": "https://ess.aliyuncs.com",
      "eu-west-1": "https://ess.eu-west-1.aliyuncs.com"
    }
  },
  {
    "name": "Oss",
    "version": "2018-01-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "对象存储",
    "showNameEn": "Object Storage Service",
    "shortName": "OSS",
    "apiDocOverviewId": "31948",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "http://oss.aliyuncs.com" }
  },
  {
    "name": "Vpc",
    "version": "2016-04-28",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "专有网络",
    "showNameEn": "Virtual Private Cloud",
    "shortName": "VPC",
    "apiDocOverviewId": "34962",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": "ActiveFlowLog,DeleteFlowLog,DescribeFlowLogs,ModifyFlowLogAttribute,CreateFlowLog,DeactiveFlowLog,DeleteExpressConnect",
    "endpoint": {
      "default": "https://vpc.aliyuncs.com",
      "cn-hangzhou": "https://vpc.aliyuncs.com",
      "cn-beijing": "https://vpc.aliyuncs.com",
      "cn-qingdao": "https://vpc.aliyuncs.com",
      "cn-zhangjiakou": "https://vpc.cn-zhangjiakou.aliyuncs.com",
      "cn-huhehaote": "https://vpc.cn-huhehaote.aliyuncs.com",
      "cn-shanghai": "https://vpc.aliyuncs.com",
      "cn-shenzhen": "https://vpc.aliyuncs.com",
      "cn-hongkong": "https://vpc.aliyuncs.com",
      "ap-southeast-1": "https://vpc.aliyuncs.com",
      "ap-southeast-2": "https://vpc.ap-southeast-2.aliyuncs.com",
      "ap-southeast-3": "https://vpc.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://vpc.ap-southeast-5.aliyuncs.com",
      "ap-northeast-1": "https://vpc.ap-northeast-1.aliyuncs.com",
      "eu-west-1": "https://vpc.eu-west-1.aliyuncs.com",
      "us-west-1": "https://vpc.aliyuncs.com",
      "us-east-1": "https://vpc.aliyuncs.com",
      "eu-central-1": "https://vpc.eu-central-1.aliyuncs.com",
      "me-east-1": "https://vpc.me-east-1.aliyuncs.com",
      "ap-south-1": "https://vpc.ap-south-1.aliyuncs.com"
    }
  },
  {
    "name": "Ram",
    "version": "2015-05-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "访问控制",
    "showNameEn": "Resource Access Management",
    "shortName": "RAM",
    "apiDocOverviewId": "28672",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": "GetAccessKeyLastUsed,GetSecurityPreference",
    "endpoint": { "default": "https://ram.aliyuncs.com" }
  },
  {
    "name": "Sts",
    "version": "2015-04-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "安全令牌",
    "showNameEn": "Security Token Service",
    "shortName": "STS",
    "apiDocOverviewId": "28756",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://sts.aliyuncs.com" }
  },
  {
    "name": "Cms",
    "version": "2019-01-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云监控",
    "showNameEn": "Cloud Monitor",
    "shortName": "CMS",
    "apiDocOverviewId": "28615",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://metrics.aliyuncs.com",
      "cn-qingdao": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-zhangjiakou": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-huhehaote": "https://metrics.cn-huhehaote.aliyuncs.com",
      "cn-hangzhou": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "https://metrics.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "https://metrics.cn-hangzhou.aliyuncs.com",
      "ap-southeast-1": "https://metrics.cn-hangzhou.aliyuncs.com",
      "ap-southeast-2": "https://metrics.cn-hangzhou.aliyuncs.com",
      "ap-southeast-3": "https://metrics.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://metrics.ap-southeast-5.aliyuncs.com",
      "ap-northeast-1": "https://metrics.ap-northeast-1.aliyuncs.com",
      "eu-west-1": "https://metrics.eu-west-1.aliyuncs.com",
      "us-west-1": "https://metrics.cn-hangzhou.aliyuncs.com",
      "us-east-1": "https://metrics.cn-hangzhou.aliyuncs.com",
      "eu-central-1": "https://metrics.cn-hangzhou.aliyuncs.com",
      "me-east-1": "https://metrics.cn-hangzhou.aliyuncs.com",
      "ap-south-1": "https://metrics.ap-south-1.aliyuncs.com"
    }
  },
  {
    "name": "Rds",
    "version": "2014-08-15",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云数据库 RDS",
    "showNameEn": "ApsaraDB for RDS",
    "shortName": "RDS",
    "apiDocOverviewId": "26226",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": "CheckAccountNameAvailable,CheckRecoveryConditions,DescibeImportsFromDatabase,DescribeBackupDatabase,CreateDBInstanceReplica,CreateMigrateTaskForSQLServer,DescribeCharacterSetName,DescribeCollationTimeZones,CheckInstanceExist,DescribeDBInstanceByTags,DescribeDBInstancesAsCsv,DescribeDBInstancesByPerformance,DescribeMigrateTasksForSQLServer,DescribeModifyParameterLog,DescribeOssDownloadsForSQLServer,DescribeSQLLogReportList,DescribeSecurityGroupConfiguration,GrantOperatorPermission,ModifyCollationTimeZone,ModifyReadonlyInstanceDelayReplicationTime,ModifyReplicaDescription,ModifyResourceGroup,ModifySecurityGroupConfiguration,RevokeOperatorPermission,SwitchDBInstanceVpc",
    "endpoint": {
      "default": "https://rds.aliyuncs.com",
      "cn-hangzhou": "https://rds.aliyuncs.com",
      "cn-shanghai": "https://rds.aliyuncs.com",
      "cn-qingdao": "https://rds.aliyuncs.com",
      "cn-beijing": "https://rds.aliyuncs.com",
      "cn-zhangjiakou": "https://rds.cn-zhangjiakou.aliyuncs.com",
      "cn-huhehaote": "https://rds.cn-huhehaote.aliyuncs.com",
      "cn-shenzhen": "https://rds.aliyuncs.com",
      "cn-hongkong": "https://rds.aliyuncs.com",
      "ap-southeast-1": "https://rds.aliyuncs.com",
      "ap-southeast-2": "https://rds.ap-southeast-2.aliyuncs.com",
      "ap-southeast-3": "https://rds.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://rds.ap-southeast-5.aliyuncs.com",
      "ap-northeast-1": "https://rds.ap-northeast-1.aliyuncs.com",
      "eu-west-1": "https://rds.eu-west-1.aliyuncs.com",
      "us-west-1": "https://rds.aliyuncs.com",
      "us-east-1": "https://rds.aliyuncs.com",
      "eu-central-1": "https://rds.eu-central-1.aliyuncs.com",
      "me-east-1": "https://rds.me-east-1.aliyuncs.com",
      "ap-south-1": "https://rds.ap-south-1.aliyuncs.com",
      "cn-shanghai-finance-1": "https://rds.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://rds.aliyuncs.com"
    }
  },
  {
    "name": "Slb",
    "version": "2014-05-15",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "负载均衡",
    "showNameEn": "Server Load Balancer",
    "shortName": "SLB",
    "apiDocOverviewId": "27566",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-zhangjiakou": "https://slb.cn-zhangjiakou.aliyuncs.com",
      "ap-south-1": "https://slb.ap-south-1.aliyuncs.com",
      "ap-southeast-1": "https://slb.aliyuncs.com",
      "ap-northeast-1": "https://slb.ap-northeast-1.aliyuncs.com",
      "eu-west-1": "https://slb.eu-west-1.aliyuncs.com",
      "cn-shanghai-finance-1": "https://slb.aliyuncs.com",
      "ap-southeast-2": "https://slb.ap-southeast-2.aliyuncs.com",
      "eu-central-1": "https://slb.eu-central-1.aliyuncs.com",
      "cn-huhehaote": "https://slb.cn-huhehaote.aliyuncs.com",
      "default": "https://slb.aliyuncs.com",
      "cn-hangzhou": "https://slb.aliyuncs.com",
      "cn-shanghai": "https://slb.aliyuncs.com",
      "cn-shenzhen": "https://slb.aliyuncs.com",
      "cn-qingdao": "https://slb.aliyuncs.com",
      "cn-beijing": "https://slb.aliyuncs.com",
      "us-west-1": "https://slb.aliyuncs.com",
      "us-east-1": "https://slb.aliyuncs.com",
      "ap-southeast-3": "https://slb.ap-southeast-3.aliyuncs.com",
      "cn-chengdu": "https://slb.cn-chengdu.aliyuncs.com",
      "me-east-1": "https://slb.me-east-1.aliyuncs.com",
      "ap-southeast-5": "https://slb.ap-southeast-5.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://slb.aliyuncs.com",
      "cn-hongkong": "https://slb.aliyuncs.com"
    }
  },
  {
    "name": "Dds",
    "version": "2015-12-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云数据库 MongoDB",
    "showNameEn": "ApsaraDB for MongoDB",
    "shortName": "MongoDB",
    "apiDocOverviewId": "61715",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://mongodb.aliyuncs.com",
      "cn-hangzhou": "https://mongodb.aliyuncs.com",
      "cn-shanghai": "https://mongodb.aliyuncs.com",
      "cn-qingdao": "https://mongodb.aliyuncs.com",
      "cn-beijing": "https://mongodb.aliyuncs.com",
      "cn-chengdu": "https://mongodb.cn-chengdu.aliyuncs.com",
      "cn-shenzhen": "https://mongodb.aliyuncs.com",
      "cn-huhehaote": "https://mongodb.cn-huhehaote.aliyuncs.com",
      "me-east-1": "https://mongodb.me-east-1.aliyuncs.com",
      "ap-south-1": "https://mongodb.ap-south-1.aliyuncs.com",
      "ap-southeast-2": "https://mongodb.ap-southeast-2.aliyuncs.com",
      "cn-zhangjiakou": "https://mongodb.cn-zhangjiakou.aliyuncs.com",
      "ap-southeast-3": "https://mongodb.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://mongodb.ap-southeast-5.aliyuncs.com",
      "eu-central-1": "https://mongodb.eu-central-1.aliyuncs.com",
      "eu-west-1": "https://mongodb.eu-west-1.aliyuncs.com"
    }
  },
  {
    "name": "polardb",
    "version": "2017-08-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云数据库 POLARDB",
    "showNameEn": "ApsaraDB for POLARDB",
    "shortName": "POLARDB",
    "apiDocOverviewId": "58609",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://polardb.aliyuncs.com",
      "cn-huhehaote": "https://polardb.cn-huhehaote.aliyuncs.com",
      "cn-qingdao": "https://polardb.aliyuncs.com",
      "cn-beijing": "https://polardb.aliyuncs.com",
      "cn-hangzhou": "https://polardb.aliyuncs.com",
      "cn-shanghai": "https://polardb.aliyuncs.com",
      "ap-southeast-5": "https://polardb.ap-southeast-5.aliyuncs.com",
      "ap-south-1": "https://polardb.ap-south-1.aliyuncs.com"
    }
  },
  {
    "name": "R-kvstore",
    "version": "2015-01-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云数据库 Redis",
    "showNameEn": "ApsaraDB for Redis",
    "shortName": "Redis",
    "apiDocOverviewId": "60831",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://r-kvstore.aliyuncs.com",
      "cn-beijing": "https://r-kvstore.aliyuncs.com",
      "cn-huhehaote": "https://r-kvstore.cn-huhehaote.aliyuncs.com",
      "me-east-1": "https://r-kvstore.me-east-1.aliyuncs.com",
      "ap-northeast-1": "https://r-kvstore.ap-northeast-1.aliyuncs.com",
      "ap-southeast-5": "https://r-kvstore.ap-southeast-5.aliyuncs.com",
      "cn-hongkong": "https://r-kvstore.cn-hongkong.aliyuncs.com",
      "ap-southeast-1": "https://r-kvstore.ap-southeast-1.aliyuncs.com",
      "ap-southeast-3": "https://r-kvstore.ap-southeast-3.aliyuncs.com",
      "ap-southeast-2": "https://r-kvstore.ap-southeast-2.aliyuncs.com",
      "ap-south-1": "https://r-kvstore.ap-south-1.aliyuncs.com",
      "eu-central-1": "https://r-kvstore.eu-central-1.aliyuncs.com",
      "cn-zhangjiakou": "https://r-kvstore.cn-zhangjiakou.aliyuncs.com",
      "cn-shanghai": "https://r-kvstore.aliyuncs.com",
      "cn-qingdao": "https://r-kvstore.aliyuncs.com",
      "cn-hangzhou": "https://r-kvstore.aliyuncs.com",
      "cn-shenzhen": "https://r-kvstore.aliyuncs.com"
    }
  },
  {
    "name": "HBase",
    "version": "2017-01-15",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云数据库 HBase",
    "showNameEn": "ApsaraDB for HBase",
    "shortName": "HBase",
    "apiDocOverviewId": "49055",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://hbase.aliyuncs.com",
      "cn-huhehaote": "https://hbase.cn-huhehaote.aliyuncs.com",
      "me-east-1": "https://hbase.me-east-1.aliyuncs.com",
      "ap-southeast-2": "https://hbase.ap-southeast-2.aliyuncs.com",
      "ap-southeast-3": "https://hbase.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://hbase.ap-southeast-5.aliyuncs.com",
      "ap-south-1": "https://hbase.ap-south-1.aliyuncs.com",
      "eu-central-1": "https://hbase.eu-central-1.aliyuncs.com"
    }
  },
  {
    "name": "hitsdb",
    "version": "2017-06-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "时序时空数据库 HiTSDB",
    "showNameEn": "ApsaraDB for HiTSDB",
    "shortName": "HiTSDB",
    "apiDocOverviewId": "62386",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://hitsdb.aliyuncs.com" }
  },
  {
    "name": "Cdn",
    "version": "2018-05-10",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "内容分发",
    "showNameEn": "CDN",
    "shortName": "CDN",
    "apiDocOverviewId": "27155",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": "AddFCTrigger,DeleteFCTrigger,DescribeDomainCname,DescribeFCTrigger,UpdateFCTrigger",
    "endpoint": { "default": "http://cdn.aliyuncs.com" }
  },
  {
    "name": "Cbn",
    "version": "2017-09-12",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云企业网",
    "showNameEn": "Cloud Enterprise Network",
    "shortName": "CEN",
    "apiDocOverviewId": "",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://cbn.aliyuncs.com" }
  },
  {
    "name": "Emr",
    "version": "2016-04-08",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "E-MapReduce",
    "showNameEn": "E-MapReduce",
    "shortName": "EMR",
    "apiDocOverviewId": "28140",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://emr.aliyuncs.com",
      "cn-huhehaote": "https://emr.cn-huhehaote.aliyuncs.com",
      "ap-south-1": "https://emr.ap-south-1.aliyuncs.com",
      "me-east-1": "https://emr.me-east-1.aliyuncs.com",
      "us-east-1": "https://emr.us-east-1.aliyuncs.com",
      "ap-northeast-1": "https://emr.ap-northeast-1.aliyuncs.com",
      "ap-southeast-2": "https://emr.ap-southeast-2.aliyuncs.com",
      "ap-southeast-3": "https://emr.ap-southeast-3.aliyuncs.com",
      "ap-southeast-5": "https://emr.ap-southeast-5.aliyuncs.com",
      "eu-central-1": "https://emr.eu-central-1.aliyuncs.com",
      "cn-zhangjiakou": "https://emr.cn-zhangjiakou.aliyuncs.com"
    }
  },
  {
    "name": "EHPC",
    "version": "2018-04-12",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "弹性高性能计算",
    "showNameEn": "Elastic High Performance Computing",
    "shortName": "E-HPC",
    "apiDocOverviewId": "57889",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,php,python,java,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "http://ehpc.cn-hangzhou.aliyuncs.com",
      "cn-qingdao": "http://ehpc.cn-qingdao.aliyuncs.com",
      "cn-beijing": "http://ehpc.cn-beijing.aliyuncs.com",
      "cn-zhangjiakou": "http://ehpc.cn-zhangjiakou.aliyuncs.com",
      "cn-hangzhou": "http://ehpc.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "http://ehpc.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "http://ehpc.cn-shenzhen.aliyuncs.com",
      "ap-southeast-1": "http://ehpc.ap-southeast-1.aliyuncs.com",
      "cn-huhehaote": "http://ehpc.cn-huhehaote.aliyuncs.com",
      "cn-hongkong": "http://ehpc.cn-hongkong.aliyuncs.com",
      "eu-central-1": "http://ehpc.eu-central-1.aliyuncs.com"
    }
  },
  {
    "name": "saf",
    "version": "2017-03-31",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "风险识别",
    "showNameEn": "Fraud Detection",
    "shortName": "SAF",
    "apiDocOverviewId": "70057",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,java,python,php,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://saf.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "Actiontrail",
    "version": "2017-12-04",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "操作审计",
    "showNameEn": "ActionTrail",
    "shortName": "ActionTrail",
    "apiDocOverviewId": "28832",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://actiontrail.cn-hangzhou.aliyuncs.com/actiontrail",
      "cn-huhehaote": "https://actiontrail.cn-huhehaote.aliyuncs.com",
      "ap-south-1": "https://actiontrail.ap-south-1.aliyuncs.com",
      "cn-beijing": "https://actiontrail.cn-beijing.aliyuncs.com",
      "me-east-1": "https://actiontrail.me-east-1.aliyuncs.com",
      "us-east-1": "https://actiontrail.us-east-1.aliyuncs.com",
      "ap-northeast-1": "https://actiontrail.ap-northeast-1.aliyuncs.com",
      "ap-southeast-2": "https://actiontrail.ap-southeast-2.aliyuncs.com",
      "cn-shanghai": "https://actiontrail.cn-shanghai.aliyuncs.com",
      "cn-hongkong": "https://actiontrail.cn-hongkong.aliyuncs.com",
      "cn-shenzhen": "https://actiontrail.cn-shenzhen.aliyuncs.com",
      "ap-southeast-3": "https://actiontrail.ap-southeast-3.aliyuncs.com",
      "cn-hangzhou": "https://actiontrail.cn-hangzhou.aliyuncs.com",
      "ap-southeast-5": "https://actiontrail.ap-southeast-5.aliyuncs.com",
      "ap-southeast-1": "https://actiontrail.ap-southeast-1.aliyuncs.com",
      "us-west-1": "https://actiontrail.us-west-1.aliyuncs.com",
      "eu-central-1": "https://actiontrail.eu-central-1.aliyuncs.com",
      "cn-zhangjiakou": "https://actiontrail.cn-zhangjiakou.aliyuncs.com"
    }
  },
  {
    "name": "aegis",
    "version": "2016-11-11",
    "apiStyle": "RPC",
    "category": "云安全",
    "showName": "云安全中心（安骑士）",
    "showNameEn": "Server Guard",
    "shortName": "aegis",
    "apiDocOverviewId": "109313",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://aegis.cn-hangzhou.aliyuncs.com",
      "ap-southeast-3": "https://aegis.ap-southeast-3.aliyuncs.com",
      "cn-hangzhou": "https://aegis.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "Airec",
    "version": "2018-10-12",
    "apiStyle": "ROA",
    "category": "大数据应用",
    "showName": "智能推荐",
    "showNameEn": "AIRec",
    "shortName": "AIRec",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-hangzhou": "https://airec.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://airec.cn-beijing.aliyuncs.com",
      "cn-shanghai": "https://airec.cn-shanghai.aliyuncs.com"
    }
  },
  {
    "name": "Alidns",
    "version": "2015-01-09",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云解析",
    "showNameEn": "Cloud DNS",
    "shortName": "DNS",
    "apiDocOverviewId": "29740",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://alidns.aliyuncs.com" }
  },
  {
    "name": "alikafka",
    "version": "2018-10-15",
    "apiStyle": "RPC",
    "category": "互联网中间件",
    "showName": "消息队列 Kafka",
    "showNameEn": "MQ for Kafka",
    "shortName": "alikafka",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,php",
    "supportPopDoc": 1,
    "hiddenApi": "DeleteConsumerGroup,DeleteTopic,GetAllInstanceIdList",
    "endpoint": {
      "ap-southeast-1": "https://alikafka.ap-southeast-1.aliyuncs.com",
      "cn-huhehaote": "https://alikafka.cn-huhehaote.aliyuncs.com",
      "ap-south-1": "https://alikafka.ap-south-1.aliyuncs.com",
      "ap-southeast-5": "https://alikafka.ap-southeast-5.aliyuncs.com",
      "cn-hongkong": "https://alikafka.cn-hongkong.aliyuncs.com",
      "cn-qingdao": "https://alikafka.cn-qingdao.aliyuncs.com",
      "cn-shanghai": "https://alikafka.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "https://alikafka.cn-shenzhen.aliyuncs.com",
      "cn-zhangjiakou": "https://alikafka.cn-zhangjiakou.aliyuncs.com",
      "cn-hangzhou": "https://alikafka.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://alikafka.cn-beijing.aliyuncs.com"
    }
  },
  {
    "name": "antiddos-public",
    "version": "2017-05-18",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "DDoS 防护",
    "showNameEn": "DDoS",
    "shortName": "DDOS",
    "apiDocOverviewId": "92122",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "http://antiddos.aliyuncs.com", "cn-hangzhou": "http://antiddos.aliyuncs.com" }
  },
  {
    "name": "ARMS",
    "version": "2019-08-08",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "业务实时监控服务",
    "showNameEn": "RealTime Monitoring Service",
    "shortName": "ARMS",
    "apiDocOverviewId": "42924",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://arms.aliyuncs.com",
      "cn-beijing": "https://arms.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "https://arms.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://arms.cn-shanghai.aliyuncs.com",
      "cn-hongkong": "https://arms.cn-hongkong.aliyuncs.com",
      "ap-southeast-1": "https://arms.ap-southeast-1.aliyuncs.com",
      "cn-shenzhen": "https://arms.cn-shenzhen.aliyuncs.com",
      "cn-qingdao": "https://arms.cn-qingdao.aliyuncs.com"
    }
  },
  {
    "name": "avds",
    "version": "2017-11-29",
    "apiStyle": "RPC",
    "category": "安全",
    "showName": "漏洞扫描",
    "showNameEn": "Cloud Security Scanner",
    "shortName": "CSS",
    "apiDocOverviewId": "65268",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://avds.aliyuncs.com", "cn-hangzhou": "https://avds.aliyuncs.com" }
  },
  {
    "name": "Baas",
    "version": "2018-12-21",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "区块链服务",
    "showNameEn": "Blockchain as a Service",
    "shortName": "BaaS",
    "apiDocOverviewId": "84950",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://baas.cn-hangzhou.aliyuncs.com",
      "ap-northeast-1": "https://baas.ap-southeast-1.aliyuncs.com",
      "ap-southeast-1": "https://baas.ap-southeast-1.aliyuncs.com",
      "cn-hongkong": "https://baas.ap-southeast-1.aliyuncs.com",
      "cn-hangzhou": "https://baas.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://baas.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://baas.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "https://baas.cn-hangzhou.aliyuncs.com",
      "us-east-1": "https://baas.ap-southeast-1.aliyuncs.com/",
      "eu-central-1": "https://baas.ap-southeast-1.aliyuncs.com/"
    }
  },
  {
    "name": "BatchCompute",
    "version": "2015-11-11",
    "apiStyle": "ROA",
    "category": "弹性计算",
    "showName": "批量计算",
    "showNameEn": "BatchCompute",
    "shortName": "暂无",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hongkong": "https://batchcompute.cn-hongkong.aliyuncs.com" }
  },
  {
    "name": "BssOpenApi",
    "version": "2017-12-14",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "阿里云 Billing",
    "showNameEn": "Alibaba Cloud Billing",
    "shortName": "Billing",
    "apiDocOverviewId": "88067",
    "isNeedActive": true,
    "activeUrl": {
      "url": "http://page.aliyun.com/form/act522746710/index.htm",
      "url_intl": "http://page-intl.aliyun.com/form/Aliclou_Billing_Management_OpenAPI/index.htm"
    },
    "description": { "zh": "", "en": "" },
    "isCommercialize": false,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": "QueryMonthlyBill,QueryMonthlyInstanceConsumption,QuerySettlementBill",
    "endpoint": {
      "default": "https://business.aliyuncs.com",
      "cn-hangzhou": "https://business.aliyuncs.com",
      "ap-southeast-1": "https://business.ap-southeast-1.aliyuncs.com"
    }
  },
  {
    "name": "cas",
    "version": "2018-07-13",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "证书服务",
    "showNameEn": "SSL Service",
    "shortName": "SSL",
    "apiDocOverviewId": "28533",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://cas.aliyuncs.com" }
  },
  {
    "name": "CCC",
    "version": "2017-07-05",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云呼叫中心",
    "showNameEn": "Cloud Call Center",
    "shortName": "CC",
    "apiDocOverviewId": "85542",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://ccc.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://ccc.cn-shanghai.aliyuncs.com",
      "cn-hangzhou": "https://ccc.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "Chatbot",
    "version": "2017-10-11",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云小蜜",
    "showNameEn": "Intelligent Service Robot",
    "shortName": "ISR",
    "apiDocOverviewId": "60453",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://chatbot.cn-shanghai.aliyuncs.com",
      "cn-shanghai": "https://chatbot.cn-shanghai.aliyuncs.com",
      "cn-hangzhou": "https://chatbot.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "cityvisual",
    "version": "2018-10-30",
    "apiStyle": "RPC",
    "category": "人工智能产品",
    "showName": "城市视觉智能引擎",
    "showNameEn": "City Visual Intelligence Engine",
    "shortName": "CVIE",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-shanghai": "https://cityvisual.cn-shanghai.aliyuncs.com",
      "cn-hangzhou": "https://cityvisual.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "CloudAPI",
    "version": "2016-07-14",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "API 网关",
    "showNameEn": "API Gateway",
    "shortName": "API Gateway",
    "apiDocOverviewId": "43597",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://apigateway.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://apigateway.cn-shanghai.aliyuncs.com",
      "cn-qingdao": "https://apigateway.cn-qingdao.aliyuncs.com",
      "cn-beijing": "https://apigateway.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "https://apigateway.cn-hangzhou.aliyuncs.com",
      "ap-northeast-1": "https://apigateway.ap-northeast-1.aliyuncs.com",
      "us-west-1": "https://apigateway.us-west-1.aliyuncs.com",
      "ap-southeast-5": "https://apigateway.ap-southeast-5.aliyuncs.com",
      "cn-hongkong": "https://apigateway.cn-hongkong.aliyuncs.com",
      "cn-shenzhen": "https://apigateway.cn-shenzhen.aliyuncs.com",
      "ap-southeast-3": "https://apigateway.ap-southeast-3.aliyuncs.com",
      "ap-southeast-2": "https://apigateway.ap-southeast-2.aliyuncs.com",
      "ap-southeast-1": "https://apigateway.ap-southeast-1.aliyuncs.com",
      "ap-south-1": "https://apigateway.ap-south-1.aliyuncs.com",
      "eu-central-1": "https://apigateway.eu-central-1.aliyuncs.com"
    }
  },
  {
    "name": "Cloudauth",
    "version": "2019-03-07",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "实人认证",
    "showNameEn": "ID Verification",
    "shortName": "ID",
    "apiDocOverviewId": "57049",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://cloudauth.aliyuncs.com" }
  },
  {
    "name": "Cloudfw",
    "version": "2017-12-07",
    "apiStyle": "RPC",
    "category": "网络安全",
    "showName": "云防火墙",
    "showNameEn": "Cloud Firewall",
    "shortName": "CFW\n",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "ap-southeast-1": "https://cloudfw.ap-southeast-1.aliyuncs.com",
      "cn-hangzhou": "https://cloudfw.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "CloudPhoto",
    "version": "2017-07-11",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "智能云相册",
    "showNameEn": "Cloud Photos",
    "shortName": "CP",
    "apiDocOverviewId": "59902",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://cloudphoto.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "composer",
    "version": "2018-12-12",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "逻辑编排",
    "showNameEn": "Logic Composer",
    "shortName": "LC",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "cn-shanghai": "https://composer.cn-shanghai.aliyuncs.com", "cn-hangzhou": "https://composer.cn-hangzhou.aliyuncs.com" }
  },
  {
    "name": "CS",
    "version": "2015-12-15",
    "apiStyle": "ROA",
    "category": "cloud_basic",
    "showName": "容器服务",
    "showNameEn": "Container Service",
    "shortName": "CS",
    "apiDocOverviewId": "25972",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "http://cs.aliyuncs.com" }
  },
  {
    "name": "dataworks-public",
    "version": "2018-06-01",
    "apiStyle": "RPC",
    "category": "",
    "showName": "DataWorks",
    "showNameEn": "DataWorks",
    "shortName": "DataWorks",
    "apiDocOverviewId": "100852",
    "isNeedActive": false,
    "activeUrl": { "url": "https://data.aliyun.com/product/ide", "url_intl": "https://intl.aliyun.com/product/ide" },
    "description": {
      "zh": "DataWorks是一个提供了大数据OS能力、并以all in one box的方式提供专业高效、安全可靠的一站式大数据智能云研发平台。 同时能满足用户对数据治理、质量管理需求，赋予用户对外提供数据服务的能力。",
      "en": "A secure environment for offline data development, with powerful Open APIs, to create an ecosystem for redevelopment."
    },
    "isCommercialize": false,
    "supportCli": 0,
    "supportSdkLanguage": "java",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://dataworks.aliyuncs.com",
      "cn-shanghai": "https://dataworks.cn-shanghai.aliyuncs.com",
      "ap-northeast-1": "https://dataworks.ap-northeast-1.aliyuncs.com"
    }
  },
  {
    "name": "dcdn",
    "version": "2018-01-15",
    "apiStyle": "RPC",
    "category": "category_network",
    "showName": "全站加速",
    "showNameEn": " Dynamic Route for CDN ",
    "shortName": "DCDN",
    "apiDocOverviewId": "91679",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": {
      "zh": "旨在提升动静态资源混合站点的访问体验，支持静态资源边缘缓存，动态内容最优路由回源传输，同时满足整体站点的全网访问速度及稳定性需求。全站加速构建于阿里云CDN平台之上，适用于动静混合型、纯动态型站点或应用的内容分发加速服务",
      "en": "Dynamic Route For CDN (DCDN) is a high-performance, reliable, and secure full site acceleration solution. This service aims to accelerate access to hybrid sites that use both dynamic and static resources. DCDN integrates multiple products and services, such as dynamic acceleration systems, smart static content caching, HTTPS, and operations security. You can use DCDN to both speed-up access and ensure the stability of your site."
    },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,go,php,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "ap-northeast-1": "https://dcdn.aliyuncs.com",
      "cn-hangzhou": "https://dcdn.aliyuncs.com",
      "ap-southeast-1": "https://dcdn.aliyuncs.com",
      "default": "https://dcdn.aliyuncs.com"
    }
  },
  {
    "name": "ddosbgp",
    "version": "2018-07-20",
    "apiStyle": "RPC",
    "category": "安全",
    "showName": "DDoS防护包",
    "showNameEn": "Protection Package",
    "shortName": "ddosbgp",
    "apiDocOverviewId": "119201",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://ddosbgp.aliyuncs.com",
      "cn-hangzhou": "https://ddosbgp.aliyuncs.com",
      "cn-hongkong": "https://ddosbgp.cn-hongkong.aliyuncs.com",
      "ap-southeast-1": "https://ddosbgp.ap-southeast-1.aliyuncs.com",
      "us-east-1": "https://ddosbgp.us-east-1.aliyuncs.com",
      "us-west-1": "https://ddosbgp.us-west-1.aliyuncs.com"
    }
  },
  {
    "name": "ddoscoo",
    "version": "2017-12-28",
    "apiStyle": "RPC",
    "category": "安全（云盾）",
    "showName": "新BGP高防IP",
    "showNameEn": "BGP-line Anti-DDoS Pro",
    "shortName": "DDosCoo",
    "apiDocOverviewId": "69319",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-hangzhou": "https://ddoscoo.cn-hangzhou.aliyuncs.com",
      "ap-southeast-1": "https://ddoscoo.ap-southeast-1.aliyuncs.com"
    }
  },
  {
    "name": "DDoSPro",
    "version": "2017-07-25",
    "apiStyle": "RPC",
    "category": "网络安全",
    "showName": "DDoS高防IP",
    "showNameEn": "Anti-DDoS Pro",
    "shortName": "ddos",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://ddospro.cn-hangzhou.aliyuncs.com", "cn-hongkong": "https://ddospro.cn-hongkong.aliyuncs.com" }
  },
  {
    "name": "Dm",
    "version": "2015-11-23",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "邮件推送",
    "showNameEn": "DirectMail",
    "shortName": "DM",
    "apiDocOverviewId": "29435",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://dm.aliyuncs.com",
      "ap-southeast-1": "https://dm.ap-southeast-1.aliyuncs.com",
      "ap-southeast-2": "https://dm.ap-southeast-2.aliyuncs.com"
    }
  },
  {
    "name": "dms-enterprise",
    "version": "2018-11-01",
    "apiStyle": "RPC",
    "category": "数据库",
    "showName": "数据管理",
    "showNameEn": "Data Management",
    "shortName": "DMS",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,go,csharp,python",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "ap-northeast-1": "https://dms-enterprise.aliyuncs.com",
      "cn-shenzhen": "https://dms-enterprise.aliyuncs.com",
      "cn-shanghai": "https://dms-enterprise.aliyuncs.com",
      "cn-beijing": "https://dms-enterprise.aliyuncs.com",
      "cn-hangzhou": "https://dms-enterprise.aliyuncs.com",
      "cn-qingdao": "https://dms-enterprise.aliyuncs.com"
    }
  },
  {
    "name": "Domain",
    "version": "2018-01-29",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "域名服务",
    "showNameEn": "Domain",
    "shortName": "Domain",
    "apiDocOverviewId": "67789",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": "SaveTaskForSubmittingDomainDelete",
    "endpoint": { "default": "https://domain.aliyuncs.com", "ap-southeast-1": "https://domain-intl.aliyuncs.com" }
  },
  {
    "name": "Drds",
    "version": "2019-01-23",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "分布式关系型数据库 DRDS",
    "showNameEn": "Distributed Relational Database Service",
    "shortName": "DRDS",
    "apiDocOverviewId": "51122",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,go,csharp,python,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://drds.aliyuncs.com", "ap-southeast-1": "https://drds.ap-southeast-1.aliyuncs.com" }
  },
  {
    "name": "Dts",
    "version": "2018-08-01",
    "apiStyle": "RPC",
    "category": "迁移",
    "showName": "数据传输",
    "showNameEn": "Data Transmission",
    "shortName": "DTS",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,go,python,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "http://dts.aliyuncs.com" }
  },
  {
    "name": "Dycdpapi",
    "version": "2018-06-10",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云通信流量服务",
    "showNameEn": "Cellular Data Package",
    "shortName": "DYCDP",
    "apiDocOverviewId": null,
    "isNeedActive": true,
    "activeUrl": { "url": "https://dycdp.console.aliyun.com/dycdp.htm", "url_intl": "https://dycdp.console.aliyun.com/dycdp.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://dycdpapi.aliyuncs.com", "cn-hangzhou": "https://dycdpapi.aliyuncs.com" }
  },
  {
    "name": "Dyiotapi",
    "version": "2017-11-11",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "物联网无线连接服务",
    "showNameEn": "IoT Wireless Service",
    "shortName": "DYIOT",
    "apiDocOverviewId": "57758",
    "isNeedActive": true,
    "activeUrl": { "url": "https://dyiot.console.aliyun.com/dyiot.htm", "url_intl": "https://dyiot.console.aliyun.com/dyiot.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://dyiotapi.aliyuncs.com", "cn-hangzhou": "https://dyiotapi.aliyuncs.com" }
  },
  {
    "name": "Dyplsapi",
    "version": "2017-05-25",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "号码隐私保护服务",
    "showNameEn": "Phone Number Protection",
    "shortName": "DYPLS",
    "apiDocOverviewId": "59773",
    "isNeedActive": true,
    "activeUrl": { "url": "https://dypls.console.aliyun.com/dypls.htm", "url_intl": "https://dypls.console.aliyun.com/dypls.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://dyplsapi.aliyuncs.com", "cn-hangzhou": "https://dyplsapi.aliyuncs.com" }
  },
  {
    "name": "Dypnsapi",
    "version": "2017-05-25",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云通信号码认证服务",
    "showNameEn": "Phone Number Verification Service",
    "shortName": "DYPNS",
    "apiDocOverviewId": "84540",
    "isNeedActive": true,
    "activeUrl": { "url": "https://dypns.console.aliyun.com/dypns.htm", "url_intl": "https://dypns.console.aliyun.com/dypns.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "php,java",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://dypnsapi.aliyuncs.com", "cn-hangzhou": "https://dypnsapi.aliyuncs.com" }
  },
  {
    "name": "Dysmsapi",
    "version": "2017-05-25",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "短信服务",
    "showNameEn": "Short Message Service",
    "shortName": "DYSMS",
    "apiDocOverviewId": "55284",
    "isNeedActive": true,
    "activeUrl": { "url": "https://dysms.console.aliyun.com/dysms.htm", "url_intl": "https://dysms.console.aliyun.com/dysms.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://dysmsapi.aliyuncs.com", "cn-hangzhou": "https://dysmsapi.aliyuncs.com" }
  },
  {
    "name": "Dyvmsapi",
    "version": "2017-05-25",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云通信语音服务",
    "showNameEn": "Voice Messaging Service",
    "shortName": "DYVMS",
    "apiDocOverviewId": "55070",
    "isNeedActive": true,
    "activeUrl": { "url": "https://dyvms.console.aliyun.com/dyvms.htm", "url_intl": "https://dyvms.console.aliyun.com/dyvms.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,php,python,java,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://dyvmsapi.aliyuncs.com", "cn-hangzhou": "https://dyvmsapi.aliyuncs.com" }
  },
  {
    "name": "Eci",
    "version": "2018-08-08",
    "apiStyle": "RPC",
    "category": "弹性计算",
    "showName": "弹性容器实例 ECI",
    "showNameEn": "Elastic Container Instance",
    "shortName": "ECI",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "http://aaa.com", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-hongkong": "https://eci.aliyuncs.com",
      "us-east-1": "https://eci.aliyuncs.com",
      "cn-shenzhen": "https://eci.aliyuncs.com",
      "eu-west-1": "https://eci.eu-west-1.aliyuncs.com",
      "ap-southeast-1": "https://eci.aliyuncs.com",
      "eu-central-1": "https://eci.eu-central-1.aliyuncs.com",
      "cn-zhangjiakou": "https://eci.cn-zhangjiakou.aliyuncs.com",
      "cn-shanghai": "https://eci.aliyuncs.com",
      "cn-huhehaote": "https://eci.cn-huhehaote.aliyuncs.com",
      "cn-beijing": "https://eci.aliyuncs.com",
      "us-west-1": "https://eci.aliyuncs.com",
      "cn-hangzhou": "https://eci.aliyuncs.com",
      "ap-southeast-2": "https://eci.ap-southeast-2.aliyuncs.com"
    }
  },
  {
    "name": "Edas",
    "version": "2017-08-01",
    "apiStyle": "ROA",
    "category": "企业应用",
    "showName": "企业级分布式应用服务",
    "showNameEn": "Enterprise Distributbed Application Service",
    "shortName": "EDAS",
    "apiDocOverviewId": "62122",
    "isNeedActive": true,
    "activeUrl": { "url": "https://edas.console.aliyun.com", "url_intl": "https://edas-intl.console.aliyun.com" },
    "description": {
      "zh": "企业级分布式应用服务（Enterprise Distributed Application Service, 简称 EDAS）是一个围绕应用和微服务的PaaS平台，提供多样的应用发布和轻量级微服务解决方案，帮助用户解决在应用和服务管理过程中监控、诊断和高可用运维问题",
      "en": "Enterprise Distributed Application Service (EDAS) is a PaaS platform involving applications and microservices. It provides a variety of application release capabilities and lightweight microservice solutions that help you solve monitoring, diagnosis, and high-availability O&M issues in your application and service management processes."
    },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "php,java,python,go",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://edas.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://edas.cn-beijing.aliyuncs.com",
      "cn-qingdao": "https://edas.cn-qingdao.aliyuncs.com",
      "cn-shenzhen": "https://edas.cn-shenzhen.aliyuncs.com",
      "cn-hangzhou": "https://edas.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://edas.cn-shanghai.aliyuncs.com ",
      "ap-southeast-1": "https://edas.ap-southeast-1.aliyuncs.com"
    }
  },
  {
    "name": "Ens",
    "version": "2017-11-10",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "边缘节点服务 ENS",
    "showNameEn": "edge node service",
    "shortName": "ens",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://ens.aliyuncs.com", "cn-zhangjiakou": "https://ens.aliyuncs.com" }
  },
  {
    "name": "face",
    "version": "2018-12-03",
    "apiStyle": "RPC",
    "category": "人工智能产品",
    "showName": "人脸识别",
    "showNameEn": "Face Service",
    "shortName": "FS",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-shanghai": "https://dtplus-cn-shanghai.data.aliyuncs.com" }
  },
  {
    "name": "fnf",
    "version": "2019-03-15",
    "apiStyle": "RPC",
    "category": "弹性计算",
    "showName": "函数工作流",
    "showNameEn": "FunctionFlow",
    "shortName": "FNF",
    "apiDocOverviewId": "122650",
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=fnf#/open", "url_intl": "" },
    "description": {
      "zh": "函数工作流是一个用来协调多个分布式任务执行的全托管 Serverless 云服务。",
      "en": "Function Flow (FnF) is a fully managed cloud service that allows you to define and execute Serverless workflow that coordinates distributed tasks."
    },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php,python,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-shenzhen": "https://cn-shenzhen.fnf.aliyuncs.com",
      "cn-hangzhou": "https://cn-hangzhou.fnf.aliyuncs.com",
      "cn-shanghai": "https://cn-shanghai.fnf.aliyuncs.com"
    }
  },
  {
    "name": "foas",
    "version": "2018-11-11",
    "apiStyle": "ROA",
    "category": "大数据计算",
    "showName": "实时计算（流计算）",
    "showNameEn": "Realtime Compute（StreamCompute）",
    "shortName": "暂无",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-zhangjiakou": "https://foas.cn-zhangjiakou.aliyuncs.com",
      "cn-beijing": "https://foas.cn-beijing.aliyuncs.com",
      "ap-northeast-1": "https://foas.ap-northeast-1.aliyuncs.com",
      "cn-shenzhen": "https://foas.cn-shenzhen.aliyuncs.com",
      "ap-southeast-1": "https://foas.ap-southeast-1.aliyuncs.com",
      "cn-north-2-gov-1": "https://foas.cn-north-2-gov-1.aliyuncs.com",
      "cn-hangzhou-finance": "https://foas.cn-hangzhou-finance.aliyuncs.com",
      "public": "https://foas.aliyuncs.com",
      "cn-qingdao": "https://foas.cn-qingdao.aliyuncs.com",
      "cn-hangzhou": "https://foas.cn-hangzhou.aliyuncs.com",
      "cn-shanghai-finance-1": "https://foas.cn-shanghai-finance-1.aliyuncs.com",
      "ap-southeast-3": "https://foas.ap-southeast-3.aliyuncs.com",
      "cn-shanghai": "https://foas.cn-shanghai.aliyuncs.com"
    }
  },
  {
    "name": "gameshield",
    "version": "2018-03-05",
    "apiStyle": "RPC",
    "category": "网络安全",
    "showName": "游戏盾",
    "showNameEn": "gameshield",
    "shortName": "gameshield",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-zhangjiakou": "https://gameshield.cn-zhangjiakou.aliyuncs.com", "cn-hangzhou": "https://gameshield.aliyuncs.com" }
  },
  {
    "name": "Green",
    "version": "2018-05-09",
    "apiStyle": "ROA",
    "category": "安全",
    "showName": "内容安全",
    "showNameEn": "Alibaba Content Security Service",
    "shortName": "ACSS",
    "apiDocOverviewId": "70409",
    "isNeedActive": true,
    "activeUrl": {
      "url": "https://common-buy.aliyun.com/?commodityCode=cdi#/open",
      "url_intl": "https://common-buy-intl.aliyun.com/commodityCode=cdi_intl#/open"
    },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": "AddSimilarityLibrary,ImageAsyncScan,VoiceCancelScan,AddFaces,AddGroups,AddPerson,AddSimilarityImage,AddVideoDna,AddVideoDnaGroup,DeleteFaces,DeleteGroups,DeletePerson,DeleteSimilarityImage,DeleteSimilarityLibrary,DeleteVideoDna,DeleteVideoDnaGroup,FileAsyncScan,FileAsyncScanResults,GetAddVideoDnaResults,GetFaces,GetGroups,GetPerson,GetPersons,GetSimilarityImage,GetSimilarityLibrary,ImageAsyncScanResults,ImageScanFeedback,ListSimilarityImages,ListSimilarityLibraries,SearchPerson,SetPerson,TextFeedback,UploadCredentials,VideoFeedback,VideoSyncScan,DetectFace,VoiceIdentityUnregister,VoiceIdentityStartRegister,VoiceIdentityStartCheck,VoiceIdentityRegister,VoiceIdentityCheck",
    "endpoint": {
      "cn-hangzhou": "https://green.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://green.cn-beijing.aliyuncs.com",
      "ap-southeast-1": "https://green.ap-southeast-1.aliyuncs.com",
      "cn-shanghai": "https://green.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "https://green.cn-shenzhen.aliyuncs.com",
      "us-west-1": "https://green.us-west-1.aliyuncs.com"
    }
  },
  {
    "name": "imm",
    "version": "2017-09-06",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "智能媒体管理",
    "showNameEn": "Intelligent Media Management",
    "shortName": "IMM",
    "apiDocOverviewId": "63491",
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=imm#/open", "url_intl": "" },
    "description": {
      "zh": "场景化封装数据智能分析管理。为云上的文档、图片数据，提供一站式数据处理、分析、检索等管控体验。针对不同的业务场景，封装整合完整的处理能力，让数据快速流转。",
      "en": ""
    },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,php,python,java,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://imm.cn-hangzhou.aliyuncs.com",
      "cn-zhangjiakou": "https://imm.cn-zhangjiakou.aliyuncs.com",
      "cn-hangzhou": "https://imm.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://imm.cn-shanghai.aliyuncs.com",
      "cn-beijing": "https://imm.cn-beijing.aliyuncs.com",
      "cn-shenzhen": "https://imm.cn-shenzhen.aliyuncs.com"
    }
  },
  {
    "name": "Iot",
    "version": "2018-01-20",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "阿里云物联网平台",
    "showNameEn": "IoT Platform",
    "shortName": "IoT",
    "apiDocOverviewId": "69893",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,csharp,go",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-shanghai": "https://iot.cn-shanghai.aliyuncs.com",
      "ap-southeast-1": "https://iot.ap-southeast-1.aliyuncs.com",
      "us-west-1": "http://iot.us-west-1.aliyuncs.com",
      "ap-northeast-1": "http://iot.ap-northeast-1.aliyuncs.com",
      "eu-central-1": "http://iot.eu-central-1.aliyuncs.com",
      "default": "https://iot.cn-shanghai.aliyuncs.com"
    }
  },
  {
    "name": "iovcc",
    "version": "2018-05-01",
    "apiStyle": "RPC",
    "category": "云服务",
    "showName": "智联车管理云平台",
    "showNameEn": "IoV Command Center",
    "shortName": "ICC",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-shanghai": "https://iovcc.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "Kms",
    "version": "2016-01-20",
    "apiStyle": "RPC",
    "category": "安全管理",
    "showName": "密钥管理服务",
    "showNameEn": "KeyManagementService",
    "shortName": "KMS",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "ap-southeast-1": "https://kms.ap-southeast-1.aliyuncs.com",
      "cn-shanghai": "https://kms.cn-shanghai.aliyuncs.com",
      "ap-southeast-2": "https://kms.ap-southeast-2.aliyuncs.com",
      "cn-zhangjiakou": "https://kms.cn-zhangjiakou.aliyuncs.com",
      "ap-northeast-1": "https://kms.ap-northeast-1.aliyuncs.com",
      "cn-beijing": "https://kms.cn-beijing.aliyuncs.com",
      "cn-hangzhou": "https://kms.cn-hangzhou.aliyuncs.com",
      "eu-west-1": "https://kms.eu-west-1.aliyuncs.com",
      "eu-central-1": "https://kms.eu-central-1.aliyuncs.com",
      "ap-southeast-3": "https://kms.ap-southeast-3.aliyuncs.com",
      "cn-shanghai-finance-1": "https://kms.cn-shanghai-finance-1.aliyuncs.com",
      "cn-hongkong": "https://kms.cn-hongkong.aliyuncs.com",
      "ap-south-1": "https://kms.ap-south-1.aliyuncs.com",
      "us-east-1": "https://kms.us-east-1.aliyuncs.com",
      "us-west-1": "https://kms.us-west-1.aliyuncs.com",
      "cn-hangzhou-finance": "https://kms.cn-hangzhou-finance.aliyuncs.com",
      "ap-southeast-5": "https://kms.ap-southeast-5.aliyuncs.com",
      "cn-qingdao": "https://kms.cn-qingdao.aliyuncs.com",
      "me-east-1": "https://kms.me-east-1.aliyuncs.com",
      "cn-shenzhen": "https://kms.cn-shenzhen.aliyuncs.com",
      "cn-huhehaote": "https://kms.cn-huhehaote.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://kms.cn-shenzhen-finance-1.aliyuncs.com",
      "cn-chengdu": "https://kms.cn-chengdu.aliyuncs.com"
    }
  },
  {
    "name": "LinkWAN",
    "version": "2018-12-30",
    "apiStyle": "RPC",
    "category": "物联网络",
    "showName": "物联网络管理平台",
    "showNameEn": "Alibaba Cloud Link WAN",
    "shortName": "linkwan",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "cn-shanghai": "https://linkwan.cn-shanghai.aliyuncs.com", "cn-hangzhou": "https://linkwan.cn-hangzhou.aliyuncs.com" }
  },
  {
    "name": "live",
    "version": "2016-11-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "视频直播",
    "showNameEn": "ApsaraVideo Live",
    "shortName": "Live",
    "apiDocOverviewId": "50284",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-beijing": "https://live.aliyuncs.com",
      "cn-hangzhou": "https://live.aliyuncs.com",
      "ap-northeast-1": "https://live.aliyuncs.com",
      "cn-shanghai": "https://live.aliyuncs.com",
      "ap-southeast-1": "https://live.aliyuncs.com",
      "eu-central-1": "https://live.aliyuncs.com"
    }
  },
  {
    "name": "Market",
    "version": "2015-11-01",
    "apiStyle": "RPC",
    "category": "云市场",
    "showName": "云市场",
    "showNameEn": "aliyun marketplace",
    "shortName": "marketplace",
    "apiDocOverviewId": "30488",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "阿里云云市场，云计算的App Store", "en": "aliyun marketplace，the App Store of cloud computing." },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,php,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://market.aliyuncs.com",
      "cn-huhehaote": "https://market.aliyuncs.com",
      "me-east-1": "https://market.aliyuncs.com",
      "ap-northeast-1": "https://market.ap-southeast-1.aliyuncs.com",
      "ap-southeast-5": "https://market.ap-southeast-1.aliyuncs.com",
      "ap-southeast-3": "https://market.ap-southeast-1.aliyuncs.com",
      "ap-southeast-2": "https://market.ap-southeast-1.aliyuncs.com",
      "ap-south-1": "https://market.ap-southeast-1.aliyuncs.com",
      "eu-central-1": "https://market.ap-southeast-1.aliyuncs.com",
      "cn-zhangjiakou": "https://market.aliyuncs.com"
    }
  },
  {
    "name": "Mts",
    "version": "2014-06-18",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "媒体处理",
    "showNameEn": "ApsaraVideo for Media Processing",
    "shortName": "MTS",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-hangzhou": "https://mts.cn-hangzhou.aliyuncs.com",
      "ap-south-1": "https://mts.ap-south-1.aliyuncs.com",
      "ap-northeast-1": "https://mts.ap-northeast-1.aliyuncs.com",
      "ap-southeast-1": "https://mts.ap-southeast-1.aliyuncs.com",
      "us-west-1": "https://mts.us-west-1.aliyuncs.com",
      "cn-hongkong": "https://mts.cn-hongkong.aliyuncs.com",
      "ap-southeast-5": "https://mts.ap-southeast-5.aliyuncs.com",
      "cn-shanghai": "https://mts.cn-shanghai.aliyuncs.com",
      "eu-central-1": "https://mts.eu-central-1.aliyuncs.com",
      "cn-beijing": "https://mts.cn-beijing.aliyuncs.com",
      "cn-shenzhen": "https://mts.cn-shenzhen.aliyuncs.com",
      "cn-zhangjiakou": "https://mts.cn-zhangjiakou.aliyuncs.com",
      "eu-west-1": "https://mts.eu-west-1.aliyuncs.com"
    }
  },
  {
    "name": "NAS",
    "version": "2017-06-26",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "文件存储",
    "showNameEn": "Network Attached Storage",
    "shortName": "NAS",
    "apiDocOverviewId": "62598",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "http://nas.aliyuncs.com",
      "cn-huhehaote": "http://nas.cn-huhehaote.aliyuncs.com",
      "cn-qingdao": "http://nas.cn-qingdao.aliyuncs.com",
      "cn-beijing": "http://nas.cn-beijing.aliyuncs.com",
      "us-east-1": "http://nas.us-east-1.aliyuncs.com",
      "ap-southeast-2": "http://nas.ap-southeast-2.aliyuncs.com",
      "cn-shanghai": "http://nas.cn-shanghai.aliyuncs.com",
      "cn-hongkong": "http://nas.cn-hongkong.aliyuncs.com",
      "cn-shenzhen": "http://nas.cn-shenzhen.aliyuncs.com",
      "ap-southeast-3": "http://nas.ap-southeast-3.aliyuncs.com",
      "cn-hangzhou": "http://nas.cn-hangzhou.aliyuncs.com",
      "ap-southeast-5": "http://nas.ap-southeast-5.aliyuncs.com",
      "ap-southeast-1": "http://nas.ap-southeast-1.aliyuncs.com",
      "ap-south-1": "http://nas.ap-south-1.aliyuncs.com",
      "eu-central-1": "http://nas.eu-central-1.aliyuncs.com",
      "cn-zhangjiakou": "http://nas.cn-zhangjiakou.aliyuncs.com"
    }
  },
  {
    "name": "Nlp",
    "version": "2018-04-08",
    "apiStyle": "ROA",
    "category": "人工智能产品",
    "showName": "自然语言处理",
    "showNameEn": "Natural Language Processing",
    "shortName": "NLP",
    "apiDocOverviewId": "61384",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-shanghai": "https://nlp.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "Ons",
    "version": "2019-02-14",
    "apiStyle": "RPC",
    "category": "互联网中间件",
    "showName": "消息队列 MQ",
    "showNameEn": "Message Queue",
    "shortName": "RocketMQ",
    "apiDocOverviewId": "44419",
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=ons#/open", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-hangzhou": "https://ons.cn-hangzhou.aliyuncs.com",
      "us-east-1": "https://ons.us-east-1.aliyuncs.com",
      "cn-hongkong": "https://ons.cn-hongkong.aliyuncs.com",
      "cn-shanghai-finance-1": "https://ons.cn-shanghai-finance-1.aliyuncs.com",
      "cn-huhehaote": "https://ons.cn-huhehaote.aliyuncs.com",
      "us-west-1": "https://ons.us-west-1.aliyuncs.com",
      "cn-shenzhen": "https://ons.cn-shenzhen.aliyuncs.com",
      "me-east-1": "https://ons.me-east-1.aliyuncs.com",
      "ap-southeast-1": "https://ons.ap-southeast-1.aliyuncs.com",
      "ap-southeast-3": "https://ons.ap-southeast-3.aliyuncs.com",
      "ap-south-1": "https://ons.cn-hangzhou.aliyuncs.com",
      "eu-west-1": "https://ons.eu-west-1.aliyuncs.com",
      "eu-central-1": "https://ons.eu-central-1.aliyuncs.com",
      "ap-northeast-1": "https://ons.ap-northeast-1.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://ons.cn-shenzhen-finance-1.aliyuncs.com",
      "cn-qingdao": "https://ons.cn-qingdao.aliyuncs.com",
      "cn-chengdu": "https://ons.cn-chengdu.aliyuncs.com",
      "ap-southeast-2": "https://ons.ap-southeast-2.aliyuncs.com",
      "cn-hangzhou-finance": "https://ons.cn-hangzhou-finance.aliyuncs.com",
      "cn-zhangjiakou": "https://ons.cn-zhangjiakou.aliyuncs.com",
      "cn-shanghai": "https://ons.cn-shanghai.aliyuncs.com",
      "cn-beijing": "https://ons.cn-beijing.aliyuncs.com"
    }
  },
  {
    "name": "oos",
    "version": "2019-06-01",
    "apiStyle": "RPC",
    "category": "弹性计算",
    "showName": "运维编排",
    "showNameEn": "Operation Orchestration Service",
    "shortName": "OOS",
    "apiDocOverviewId": "120734",
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=ecs_oos#/open", "url_intl": "" },
    "description": {
      "zh": "阿里云运维编排服务（Operation Orchestration Service，简称OOS）是一个全面的云上自动化运维平台，提供了运维任务的管理和执行。",
      "en": "The Operation Orchestration Service (OOS) is a comprehensive cloud-based automated O&M platform that provides management and execution of O&M tasks."
    },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-shenzhen": "https://oos.cn-shenzhen.aliyuncs.com",
      "cn-hangzhou": "https://oos.cn-hangzhou.aliyuncs.com",
      "cn-hongkong": "https://oos.cn-hongkong.aliyuncs.com",
      "cn-shanghai": "https://oos.cn-shanghai.aliyuncs.com",
      "us-east-1": "https://oos.us-east-1.aliyuncs.com"
    }
  },
  {
    "name": "openanalytics-open",
    "version": "2018-06-19",
    "apiStyle": "RPC",
    "category": "数据库",
    "showName": "Data Lake Analytics",
    "showNameEn": "Data Lake Analytics",
    "shortName": "",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "ap-southeast-1": "https://openanalytics.ap-southeast-1.aliyuncs.com",
      "cn-beijing": "https://openanalytics.cn-beijing.aliyuncs.com",
      "cn-hongkong": "https://openanalytics.cn-hongkong.aliyuncs.com",
      "cn-shanghai": "https://openanalytics.cn-shanghai.aliyuncs.com",
      "cn-zhangjiakou": "https://openanalytics.cn-zhangjiakou.aliyuncs.com",
      "cn-hangzhou": "https://openanalytics.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "https://openanalytics.cn-shenzhen.aliyuncs.com",
      "us-west-1": "https://openanalytics.us-west-1.aliyuncs.com",
      "eu-west-1": "https://openanalytics.eu-west-1.aliyuncs.com",
      "ap-southeast-3": "https://openanalytics.ap-southeast-3.aliyuncs.com",
      "default": " https://openanalytics.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "Pcdn",
    "version": "2017-04-11",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "PCDN",
    "showNameEn": "P2P CDN",
    "shortName": "PCDN",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "http://pcdn.aliyuncs.com" }
  },
  {
    "name": "Push",
    "version": "2016-08-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "移动推送",
    "showNameEn": "Alibaba Cloud Mobile Push",
    "shortName": "CPS",
    "apiDocOverviewId": "48038",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://cloudpush.aliyuncs.com" }
  },
  {
    "name": "pvtz",
    "version": "2018-01-01",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云解析 PrivateZone",
    "showNameEn": "Alibaba Cloud DNS PrivateZone",
    "shortName": "pvtz",
    "apiDocOverviewId": "66234",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,java,python,php,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://pvtz.aliyuncs.com/" }
  },
  {
    "name": "Qualitycheck",
    "version": "2019-01-15",
    "apiStyle": "RPC",
    "category": "智能客服链接",
    "showName": "智能对话分析",
    "showNameEn": "Smart Conversation Analysis",
    "shortName": "SCA",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://qualitycheck.cn-hangzhou.aliyuncs.com" }
  },
  {
    "name": "Rdc",
    "version": "2018-08-21",
    "apiStyle": "RPC",
    "category": "开发者平台",
    "showName": "云效",
    "showNameEn": "RDC",
    "shortName": "RDC",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-beijing": "http://rdc.cn-beijing.aliyuncs.com" }
  },
  {
    "name": "ROS",
    "version": "2019-09-10",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "资源编排",
    "showNameEn": "Resource Orchestration Service",
    "shortName": "ROS",
    "apiDocOverviewId": "28899",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,php,csharp",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://ros.aliyuncs.com",
      "cn-hangzhou": "https://ros.aliyuncs.com",
      "cn-qingdao": "https://ros.aliyuncs.com",
      "cn-beijing": "https://ros.aliyuncs.com",
      "cn-zhangjiakou": "https://ros.aliyuncs.com",
      "cn-huhehaote": "https://ros.aliyuncs.com",
      "cn-shanghai": "https://ros.aliyuncs.com",
      "cn-shenzhen": "https://ros.aliyuncs.com",
      "cn-hongkong": "https://ros.aliyuncs.com",
      "ap-southeast-1": "https://ros.aliyuncs.com",
      "ap-southeast-2": "https://ros.aliyuncs.com",
      "ap-southeast-3": "https://ros.aliyuncs.com",
      "ap-southeast-5": "https://ros.aliyuncs.com",
      "ap-northeast-1": "https://ros.aliyuncs.com",
      "eu-west-1": "https://ros.aliyuncs.com",
      "us-west-1": "https://ros.aliyuncs.com",
      "us-east-1": "https://ros.aliyuncs.com",
      "eu-central-1": "https://ros.aliyuncs.com",
      "me-east-1": "https://ros.aliyuncs.com",
      "ap-south-1": "https://ros.aliyuncs.com",
      "cn-shanghai-finance-1": "https://ros.aliyuncs.com",
      "cn-shenzhen-finance-1": "https://ros.aliyuncs.com"
    }
  },
  {
    "name": "rtc",
    "version": "2018-01-11",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "音视频通信",
    "showNameEn": "Real-Time Communication",
    "shortName": "RTC",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://rtc.aliyuncs.com" }
  },
  {
    "name": "sae",
    "version": "2019-05-06",
    "apiStyle": "ROA",
    "category": "互联网中间件",
    "showName": "轻量级分布式应用服务",
    "showNameEn": "Serverless App Engine",
    "shortName": "SAE",
    "apiDocOverviewId": null,
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=sae#/buy", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-hangzhou": "https://sae.cn-hangzhou.aliyuncs.com",
      "cn-beijing": "https://sae.cn-beijing.aliyuncs.com",
      "cn-shanghai": "https://sae.cn-shanghai.aliyuncs.com"
    }
  },
  {
    "name": "Sas",
    "version": "2018-12-03",
    "apiStyle": "RPC",
    "category": "云安全",
    "showName": "云安全中心（态势感知）",
    "showNameEn": "Threat Detection Service",
    "shortName": "TDS",
    "apiDocOverviewId": "112134",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://tds.aliyuncs.com", "ap-southeast-3": "https://tds.ap-southeast-3.aliyuncs.com" }
  },
  {
    "name": "scdn",
    "version": "2017-11-15",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "安全加速 SCDN",
    "showNameEn": "scdn",
    "shortName": "scdn",
    "apiDocOverviewId": null,
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=scdn#/buy", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,java,python,php,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://scdn.aliyuncs.com" }
  },
  {
    "name": "Smartag",
    "version": "2018-03-13",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "智能接入网关",
    "showNameEn": "Smart Access Gateway",
    "shortName": "SAG",
    "apiDocOverviewId": "69845",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go,csharp",
    "supportPopDoc": 1,
    "hiddenApi": "CreateNetworkOptimization,AttachNetworkOptimizationSags,DeleteNetworkOptimization,DeleteNetworkOptimizationSetting,DetachNetworkOptimizationSags,DescribeNetworkOptimizationSettings,AddNetworkOptimizationSetting,ModifyNetworkOptimization,DescribeNetworkOptimizationSags,DescribeNetworkOptimizations",
    "endpoint": { "default": "https://smartag.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "smc",
    "version": "2019-06-01",
    "apiStyle": "RPC",
    "category": "弹性计算",
    "showName": "服务器迁移中心",
    "showNameEn": "Server Migration Center",
    "shortName": "SMC",
    "apiDocOverviewId": "25485",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "me-east-1": "https://smc.aliyuncs.com",
      "ap-southeast-1": "https://smc.aliyuncs.com",
      "cn-zhangjiakou": "https://smc.aliyuncs.com",
      "cn-shenzhen": "https://smc.aliyuncs.com",
      "cn-huhehaote": "https://smc.aliyuncs.com",
      "us-east-1": "https://smc.aliyuncs.com",
      "ap-southeast-5": "https://smc.aliyuncs.com",
      "eu-west-1": "https://smc.aliyuncs.com",
      "ap-southeast-2": "https://smc.aliyuncs.com",
      "eu-central-1": "https://smc.aliyuncs.com",
      "us-west-1": "https://smc.aliyuncs.com",
      "cn-chengdu": "https://smc.aliyuncs.com",
      "cn-hongkong": "https://smc.aliyuncs.com",
      "cn-shanghai": "https://smc.aliyuncs.com",
      "cn-hangzhou": "https://smc.aliyuncs.com",
      "ap-northeast-1": "https://smc.aliyuncs.com",
      "cn-beijing": "https://smc.aliyuncs.com",
      "ap-south-1": "https://smc.aliyuncs.com",
      "cn-qingdao": "https://smc.aliyuncs.com",
      "ap-southeast-3": "https://smc.aliyuncs.com"
    }
  },
  {
    "name": "sms-intl",
    "version": "2018-05-01",
    "apiStyle": "RPC",
    "category": "云通信",
    "showName": "国际短信服务",
    "showNameEn": "International Short Message Service",
    "shortName": "SMS-INTL",
    "apiDocOverviewId": "",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": {
      "zh": "覆盖全球的短信服务，友好、高效、智能的互联化通讯能力，帮助企业迅速搭建客户触达通道。",
      "en": "A messaging service that covers the globe, Alibaba SMS provides convenient, efficient, and intelligent communication capabilities that help businesses quickly contact their customers."
    },
    "isCommercialize": false,
    "supportCli": 0,
    "supportSdkLanguage": "php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://sms-intl.ap-southeast-1.aliyuncs.com",
      "ap-southeast-1": "https://sms-intl.ap-southeast-1.aliyuncs.com"
    }
  },
  {
    "name": "Snsuapi",
    "version": "2018-07-09",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "云通信网络加速",
    "showNameEn": "Network Acceleration Service",
    "shortName": "SNSU",
    "apiDocOverviewId": "87335",
    "isNeedActive": true,
    "activeUrl": { "url": "https://snsu.console.aliyun.com/snsu.htm", "url_intl": "https://snsu.console.aliyun.com/snsu.htm" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "go,java,python,php,csharp",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "default": "https://snsuapi.aliyuncs.com", "cn-hangzhou": "https://snsuapi.aliyuncs.com" }
  },
  {
    "name": "Uis",
    "version": "2018-08-21",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "极致互联网服务",
    "showNameEn": "Ultimate Internet Service",
    "shortName": "UIS",
    "apiDocOverviewId": "",
    "isNeedActive": true,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": false,
    "supportCli": 0,
    "supportSdkLanguage": "java,python,php,go",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://uis.cn-hangzhou.aliyuncs.com" }
  },
  {
    "name": "Vcs",
    "version": "2019-04-30",
    "apiStyle": "RPC",
    "category": "人工智能产品",
    "showName": "视觉计算服务",
    "showNameEn": "Visual Compute Service",
    "shortName": "vcs",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": { "cn-hangzhou": "https://vcs.cn-hangzhou.aliyuncs.com", "cn-shanghai": "https://vcs.cn-shanghai.aliyuncs.com" }
  },
  {
    "name": "vod",
    "version": "2017-03-21",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "视频点播",
    "showNameEn": "ApsaraVideo for VoD",
    "shortName": "VOD",
    "apiDocOverviewId": "60574",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,php",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://vod.cn-shanghai.aliyuncs.com",
      "cn-shanghai": "https://vod.cn-shanghai.aliyuncs.com",
      "cn-hangzhou": "https://vod.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "https://vod.cn-shanghai.aliyuncs.com",
      "cn-beijing": "https://vod.cn-shanghai.aliyuncs.com"
    }
  },
  {
    "name": "vs",
    "version": "2018-12-12",
    "apiStyle": "RPC",
    "category": "视频与CDN",
    "showName": "视频监控",
    "showNameEn": "video surveillance system",
    "shortName": "vs",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": "java,php,python",
    "supportPopDoc": 0,
    "hiddenApi": null,
    "endpoint": {
      "cn-beijing": "https://vs.cn-beijing.aliyuncs.com",
      "cn-shanghai": "https://vs.cn-shanghai.aliyuncs.com",
      "cn-qingdao": "https://vs.cn-qingdao.aliyuncs.com",
      "cn-hangzhou": "https://vs.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "https://vs.cn-shenzhen.aliyuncs.com"
    }
  },
  {
    "name": "waf-openapi",
    "version": "2018-01-17",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "Web 应用防火墙",
    "showNameEn": "Web Application Firewall",
    "shortName": "WAF",
    "apiDocOverviewId": "86349",
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,php",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": { "default": "https://wafopenapi.cn-hangzhou.aliyuncs.com", "cn-hangzhou": "https://wafopenapi.cn-hangzhou.aliyuncs.com" }
  },
  {
    "name": "WebPlus",
    "version": "2019-03-20",
    "apiStyle": "ROA",
    "category": "弹性计算",
    "showName": "Web应用托管服务",
    "showNameEn": "app service",
    "shortName": "webx",
    "apiDocOverviewId": null,
    "isNeedActive": true,
    "activeUrl": { "url": "https://common-buy.aliyun.com/?commodityCode=webx#/open", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 0,
    "supportSdkLanguage": null,
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "cn-beijing": "https://webplus.cn-hangzhou.aliyuncs.com",
      "cn-shenzhen": "https://webplus.cn-hangzhou.aliyuncs.com",
      "cn-hangzhou": "https://webplus.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://webplus.cn-hangzhou.aliyuncs.com",
      "cn-zhangjiakou": "https://webplus.cn-hangzhou.aliyuncs.com",
      "default": "https://webplus.cn-hangzhou.aliyuncs.com"
    }
  },
  {
    "name": "xtrace",
    "version": "2019-08-08",
    "apiStyle": "RPC",
    "category": "cloud_basic",
    "showName": "链路追踪",
    "showNameEn": "Tracing Analysis",
    "shortName": "xtrace",
    "apiDocOverviewId": null,
    "isNeedActive": false,
    "activeUrl": { "url": "", "url_intl": "" },
    "description": { "zh": "", "en": "" },
    "isCommercialize": true,
    "supportCli": 1,
    "supportSdkLanguage": "java,python,go,csharp,nodejs",
    "supportPopDoc": 1,
    "hiddenApi": null,
    "endpoint": {
      "default": "https://xtrace.aliyuncs.com",
      "cn-beijing": "https://xtrace.cn-beijing.aliyuncs.com",
      "cn-qingdao": "https://xtrace.cn-qingdao.aliyuncs.com",
      "cn-hangzhou": "https://xtrace.cn-hangzhou.aliyuncs.com",
      "cn-shanghai": "https://xtrace.cn-shanghai.aliyuncs.com",
      "cn-shenzhen": "https://xtrace.cn-shenzhen.aliyuncs.com"
    }
  }
]
